### ISSUE TITLE
xfce4-terminal is ignored

### ISSUE THREAD

**Issue by xpufx** [leukipp/cortile#1]
window_ignore = [
    ['xf.*', ''],

This is matching a bit too much. I was not able to fix the regexp myself but here's the xprop output

WM_CLASS(STRING) = "xfce4-terminal", "Xfce4-terminal"

EDIT:
I can make this work now with ['xf.*','xfce4-terminal']   . It didn't work before becausae my xfce4-terminal was set to not display the title (General/Title/Initial title and Dynamically-set title settings). I also did some looking around and the go regexp library does not seem to support the various look ahead/around etc functionality to exclude a regexp. That would have to be implemented in code if necessary.

**Comment by leukipp** [comment]
Thanks, will have a look if there is a better way to handle the various 'xf.*' windows.

**Comment by leukipp** [comment]
Global 'xf.*' match was removed from default config via ab1dfb7.
