### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by napcok** [leukipp/cortile#11]
This is not an issue, just want to thank you for this fantastic project.
I've been testing with Openbox for some time and it's very impressive.
So impressive that I'm considering integrating Cortile in the next releases of Mabox Linux. For now, I encourage [the community to give it a try](https://forum.maboxlinux.org/t/cortile-workspace-based-tiling-manager-for-openbox/1344).

I think I'll have some feature requests in the future, but for now, I want to test and get to know Cortile even more.

So thank you again and keep up the good work :+1:

**Comment by leukipp** [comment]
Thanks for your kind words and the community shout-out, I appreciate it!

It just happened that I had to setup an operating system on another machine, and I decided to install Mabox,
I really like it so far and I could get everything to work quite nicely.

What I can already tell is that cortile behaves a little bit different on Openbox than on Xfce.
Some of the features do not work as expected. I will further test it on Mabox and publish some more releases in the upcoming days.

Thanks!

**Comment by leukipp** [comment]
Starting with [v1.1.5](https://github.com/leukipp/cortile/releases/tag/v1.1.5) cortile now behaves quite similar between standard Xfce and standard Openbox environments.

I can also confirm that the drag&drop window swap now also work in Mabox, please let me know if you run into any other issues.

**Comment by napcok** [comment]
Thank you.
The progress and pace of development of Cortile are amazing. I didn't even manage to report anything because you already fixed it :)

I'm working on integrating Cortile into the next Mabox ISO. To make it as easy as possible for the user to try out Cortile, I am writing a small helper in the form of tint2 executor. Currently it's _fast and dirty_ but functional (as demo). It shows icons with the current Cortile layout for a given workspace (or untiled). With click it switches layouts. Using the mouse wheel is possible to increase/decrease aspect ratio (or switch windows if layout = fullscreen)

Please have a look: https://www.youtube.com/watch?v=sfuXrpgVaDE

One thing that makes me wonder...

To find out about the current state of a given workspace Cortile must be launched with the -v option and then I grep the logs. It works, but I don't think it's very elegant. Maybe you have another idea?

**Comment by nairdesigns** [comment]
Really awesome program! I've been looking for a wm that would be compatible with cinammon. Thank you for all your hard work!
