### ISSUE TITLE
Can I disable hot corners and keep only kbd shortcuts?

### ISSUE THREAD

**Issue by lobaluna** [leukipp/cortile#12]
Obviously, this is just a suggestion.

My mouse movement is kind of erratic, so disabling hot corners will be good for me.

I already changed these settings:
```
# Width and height of a hot-corner area within the edge corners (0 - 100).
#edge_corner_size = 10
edge_corner_size = 0

# Width or height of a hot-corner area within the edge centers (0 - 100).
#edge_center_size = 100
edge_center_size = 0
```

Maybe a config setting can help me...

**Comment by leukipp** [comment]
You can disable some/all corner events by setting an empty string. e.g.: 
```
# Corner at top center.
top_center = ""

# Corner at center right.
center_right = ""

# Corner at bottom center.
bottom_center = ""

# Corner at center left.
center_left = ""
```
will disable all the layout change events.

**Comment by lobaluna** [comment]
Thank you! And congratulations on this great project!
