### ISSUE TITLE
Status file with current workspace state?

### ISSUE THREAD

**Issue by napcok** [leukipp/cortile#13]
_Background:_
I'm working on integrating Cortile into the next Mabox ISO. To make it as easy as possible for the user to try out Cortile, I am writing a small helper in the form of tint2 executor. Currently it's _quick and dirty_ but functional (as demo). It shows icons with the current Cortile layout for a given workspace (or untiled). With click it switches layouts. Using the mouse wheel is possible to increase/decrease aspect ratio (or switch windows if layout = fullscreen)

Please have a look: https://www.youtube.com/watch?v=sfuXrpgVaDE

One thing that makes me wonder...

To find out about the current state of a given workspace Cortile must be launched with the -v option and then I grep the logs. It works, but I don't think it's very elegant. Maybe you have another idea?

**Comment by leukipp** [comment]
I'm working on a more elegant solution, using socket communication.
This will allow direct state requests from external processes (e.g. from bash scripts)

Closed in favor of #14.

**Comment by leukipp** [comment]
Please review [cortile-addons](https://github.com/leukipp/cortile-addons) and #65.
