### ISSUE TITLE
Weird interaction between tiling and sticky windows in xfce

### ISSUE THREAD

**Issue by Haxxflaxx** [leukipp/cortile#17]
Due to how xfce manages virtual desktops, I tend to stick any window that I throw up on my secondary screen, as I want them on all desktops. When doing this with tiling turned on on that screen it seems like that window is effectively removed from the tiling logic. This makes it so that any other window on that screen now takes up the full screen and the sticky one is now floating above or behind it.

It would be nice if sticky windows can be treated as any other window (just re-tiled when moving to a new desktop)

Is it possible to control if a window is sticky based on the screen it is on? That could be useful as well.

**Comment by leukipp** [comment]
> Is it possible to control if a window is sticky based on the screen it is on? That could be useful as well.

It looks like there exists an open [pull request](https://gitlab.xfce.org/xfce/xfwm4/-/merge_requests/132) for your desired [functionality](https://gitlab.xfce.org/xfce/xfwm4/-/issues/604). I would prefer a general xfce integration in favor of a cortile implementation, but I would suspect that this could be easily implemented with a standalone application using [xgb](https://github.com/BurntSushi/xgb) and [xgbutil](https://github.com/BurntSushi/xgbutil).

> It would be nice if sticky windows can be treated as any other window (just re-tiled when moving to a new desktop)

It will take some time to evaluate, but I will look into it as it seems to be a useful feature in general.

**Comment by leukipp** [comment]
> Is it possible to control if a window is sticky based on the screen it is on? That could be useful as well.

See #22 for future updates.

> It would be nice if sticky windows can be treated as any other window (just re-tiled when moving to a new desktop)

Support for sticky windows is now available in the [latest](https://github.com/leukipp/cortile/releases/latest) release.
