### ISSUE TITLE
[Feature request] Disable automated layout switch to `fullscreen`

### ISSUE THREAD

**Issue by KaKi87** [leukipp/cortile#20]
Hello,

I don't know exactly when and why Cortile does that, but I would like to be able to disable this behavior.

Thanks

**Comment by leukipp** [comment]
Besides <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Space</kbd>, the fullscreen layout is also activated if you open a maximized window. e.g. when you press the maximize window button or via shortcuts like <kbd>Alt</kbd>+<kbd>F5</kbd>, <kbd>Alt</kbd>+<kbd>Double-Click</kbd>.

**Comment by KaKi87** [comment]
Okay, I figured it out : apps open themselves maximized by default, thus triggering the `fullscreen` layout.

But, I want to force them into my current layout instead.

Thanks

**Comment by KaKi87** [comment]
Why did you close the issue ?

Thanks

**Comment by leukipp** [comment]
Thought you figured it out? 

So far cortile switching to `fullscreen` on maximization is by design. Can you find the reason why apps are open themself maximized?

**Comment by KaKi87** [comment]
What I meant is, I figured out why does the `fullscreen` layout gets activated as per your indications, but I still want a feature that prevents this layout from activating.

On Pop OS for example, which AFAIK is the only other software in the world that offers the same kind of auto-tiling as you do, the tiled layout persists regardless of apps' behavior.

Thanks

**Comment by KaKi87** [comment]
@leukipp :pray:

**Comment by KaKi87** [comment]
Hello ?
