### ISSUE TITLE
[Feature request] Remember window monitor

### ISSUE THREAD

**Issue by KaKi87** [leukipp/cortile#21]
Hello,

It would be nice of Cortile to remember on which monitor I put my windows.

Use case :

1. I launch an app.
2. It appears on monitor A.
3. I move it to monitor B.
4. I close it.
5. I launch it again.

Expected : it appears on monitor B.

Actual : it appears on monitor A.

Thanks

**Comment by leukipp** [comment]
Closed in favor of #22.

If you need more control have a look into [devilspie](https://github.com/dsalt/devilspie2).

**Comment by KaKi87** [comment]
That other link doesn't seem to be a very user-friendly thing so I guess I'll wait for your other app. Thanks
