### ISSUE TITLE
[Documentation] Prior and Next keys

### ISSUE THREAD

**Issue by xpufx** [leukipp/cortile#24]
I don't recall seeing these keys on a keyboard before. Looking at the xgbutil/keyboard source they seem to be equivalent to Page_Up (Prior) and Page_Down (Next) . Maybe this is evident to everybody else. If not, it might be good to add these keys in parantheses in the Readme and config file.

**Comment by leukipp** [comment]
Thanks for your input. I added additional information to the config section!
