### ISSUE TITLE
restart cortile may take random few seconds

### ISSUE THREAD

**Issue by vincentaxhe** [leukipp/cortile#28]
with two monitors ,I replace zentile with cortile, its a good choice.
tiling after drag window between two monitors  may not work, need to place window back and drag again which is mentioned as another issue.I use systemd service to auto restart , but restart may take few seconds, same as killall cortile and run cortile.
I rebuild cortile ,get rid of socket. but it did not work. sometimes tiling windows as soon as cortile run, but not always.
`[Unit]
Description=autotile window manager
Wants=cortile.timer

[Service]
Restart=always
RestartSec=0
RemainAfterExit=yes
ExecStart=/usr/local/bin/cortile
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=default.target`

**Comment by leukipp** [comment]
Please try the [latest](https://github.com/leukipp/cortile/releases/latest) release and let me know if the problem still occurs.

**Comment by vincentaxhe** [comment]
good work! I am surprised to get notification about new realease by systray. check the realease history I'm sure cortile is under your active development.thanks for your effort.
I try the 2.3.1 version,it starts in 1-2 secs,and can work with quicktile,drag window quickly fit in.now it is very powerful tool in many environment.though I embrace bspwm lately to feel full power of tile window. But back in xfce, I will enjoy cortile.
Last time I comment `func (tr *Tracker) handleMaximizedClient(c *store.Client) ...` to disable auto fullscreen mode, usually I just to enlarge window temporarily, after that I foundd bspwm have a monocle mode .
my service file is not accurate, put timer in service is not necessary ,and did not need a timer to delay launch.
