### ISSUE TITLE
Incorrect window placement/scaling in QT apps

### ISSUE THREAD

**Issue by abil76** [leukipp/cortile#30]
My window manager is Openbox and Cortile does not recognize the Openbox decoration specifically with QT-App. In GTK apps it recognizes the decoration without any problems. I noticed a hint in the log file as to what might be the problem. The (Tint2) panel is taken out by Cortile, which means I no longer have a 1920x1080 desktop resolution, but 1920 x 1052. My panel is 28px high, so that's fine. In the case of placing QT apps, Cortile probably uses a different resolution than GTK apps, which could explain the upward shift. Could you correct that?
![2023-11-21_17-52](https://github.com/leukipp/cortile/assets/46962320/a3bf0519-3a15-4810-b427-2bd7a27a3012)

**Comment by abil76** [comment]
It seems that with the QT apps, the resolution dimensions are taken from the value that the panel has already downscaled. Specifically, this means:

GTK app calculation of resolution = (1920x)1080px - panel height minus 28px = **1052 px** desktop height, which is adopted as the internal cortile resolution. **CORRECT**

QT app calculation of resolution=(1920x)1052 -Panel height 28px = **1024 px** desktop height which is adopted as internal cortile resolution. **INCORRECT**

So in the case of QT apps, the internal Cortile desktop only starts at 56 px (2 x 28px), because it takes the already downsampled value of 1052 px as a BASE and doesn't take 1080px again to downsample it. It pulls double duty as the Tint Panel.

This is my guess because everything points to it, and the incorrect additional scaling corresponds exactly to the height of the Tint2 Panel.

**Comment by abil76** [comment]
My previous assumption was incorrect, which is why I deleted the comment and added a more specific case description here. As can be seen from the images below, the discrepancy in scaling depends on the openbox decorations (green), especially the QT APPS. Especially in the slave window at the bottom right you can see how the distances at the very bottom edge change parallel to the title decoration size. If I enlarge the title bar, the distance to the bottom edge (top tint panel edge) becomes the same size as the Openbox title bar decoration. If I make the Openbox title bar decoration smaller, the distance below to the Tint panel edge also becomes smaller. The QT app on the right is oriented towards the GTK app on the left without taking the decoration into account, which is positioned correctly. So when scaling, the Openbox title bar is not taken into account and it is always based on the GTK app on the left without a title bar. And in the lower right QT app, a large space is added at the bottom, just like an Openbox title bar.

![2023-11-22_11-48](https://github.com/leukipp/cortile/assets/46962320/0a8b567e-8c4a-429d-9327-f147f519fdbc)
![2023-11-22_11-52](https://github.com/leukipp/cortile/assets/46962320/db773e55-4a13-4b3f-8a3c-448397384a9c)

**Comment by leukipp** [comment]
> As can be seen from the images below, the discrepancy in scaling depends on the openbox decorations (green), especially the QT APPS.

I think you are on the right track here.

Can you give a minimal example QT application that I can use for testing?
Can you confirm that the issue does not appear if you set the default config
https://github.com/leukipp/cortile/blob/7c42aea195fc375afbac7b469653eb2b11ec5100/config.toml#L62

to `window_decoration = false` ?

**Comment by abil76** [comment]
With the standard configuration "Window Decoration = false" i.e. without decoration everything works perfectly. GTK and QT apps are positioned correctly. Only if I want to have the decoration, i.e. "Window Decoration = true", then this problem arises. All QT apps lead to problems. Especially in my case it is worth mentioning the file manager "pcmanfm-qt", note program "feathernotes". But all other QT apps that I tested alternatively also led to this behavior.

**Comment by leukipp** [comment]
This should be fixed with the [latest](https://github.com/leukipp/cortile/releases/latest) release. Feel free to reopen/create an issue if you encounter any other problems.
