### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by lucarinaorg** [leukipp/cortile#32]
Can you add FreeBSD support?
thank you in advance

**Comment by leukipp** [comment]
Whats happens if you run cortile under FreeBSD? Have you already tried it using with an Openbox or XFCE environment?

**Comment by leukipp** [comment]
If you are willing to test cortile under FreeBSD and everything works as expected I could add FreeBSD releases, but it's not to hard to build cortile by yourself.

Please try to follow the [install instructions](https://github.com/leukipp/cortile/tree/main#development-) for development,  (e.g. Option 2, adjust things for FreeBSD) and run `cortile -v`. 
It should at least start and output some success/error logs that we can investigate further.

**Comment by leukipp** [comment]
FreeBSD builds are available for download, starting with version [v2.4.0](https://github.com/leukipp/cortile/releases/latest).
Let me know if you account issues during usage, which do not occur under Linux.
