### ISSUE TITLE
Adding more windows vertically 

### ISSUE THREAD

**Issue by 0A7V9A** [leukipp/cortile#33]
Hi!
Is it possible to place 3 or more windows vertically?

**Comment by leukipp** [comment]
You should be able to do the following to get a purely vertical layout:
- e.g. choose `horizontal-top` as layout (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Up</kbd>)
- decrease the number of master windows (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Minus</kbd>)

With the [latest](https://github.com/leukipp/cortile/releases/latest) release its also possible to set `window_masters_max = 0`, which completely deactivates the master-slave logic.
Feel free to reopen if you have any other questions related to this.
