### ISSUE TITLE
i don't know why these shortcut-keys not work for me

### ISSUE THREAD

**Issue by ahmeteid7** [leukipp/cortile#34]
# Tile the current workspace.
tile = "Control-Shift-T"

# Untile the current workspace.
untile = "Control-Shift-U"

# Cycles through the available layouts.
layout_cycle = "Control-Shift-C"
# Make the active window as master.
master_make = "Control-Shift-M"

**Comment by leukipp** [comment]
It could be that some of them are already in use by other applications on your system. You can try to define alternative keys in the `config.toml` file.

But it also seems that you are referring here to older (default) shortcut keys. Most of them are not used in the latest cortile release.
The latest (default) keyboard shortcuts can be found here: https://github.com/leukipp/cortile#shortcuts

**Comment by ahmeteid7** [comment]
I'm so sorry, i didn't notice that I'm using old version, I'm discovering the new version, it's perfect and have  a lot of improvements that surprise me like systray and a lots of features, that very good job, i think that app will be added as built-in in the famous distro in the near  features

**Comment by ahmeteid7** [comment]
i'm so sorry, i didn't notice that I'm using old version, I'm discovering the new version, it's perfect and have  a lot of improvements that surprise me like systray and a lots of features, that very good job, i think that app will be added as built-in in the famous distro in the near  features
