### ISSUE TITLE
can i make cortile to ignore certain workspace?

### ISSUE THREAD

**Issue by ahmeteid7** [leukipp/cortile#35]
i want cortile work on all workspace, but there is workspace i don't cortle work on it by default

**Comment by leukipp** [comment]
You could use [wmctrl](https://linux.die.net/man/1/wmctrl) in combination with cortile [socket](https://github.com/leukipp/cortile#communication-) communications to archive what you want.

Either start cortile with the config.toml value `tiling_enabled = true` and then disable tiling on a specific workspace or vice versa. e.g. This command disables tiling on a given workspace defined by `wmctrl -s <WORKSPACE INDEX>`:
```bash
wmctrl -s 0 && sleep 1 && ./send.sh -s /tmp/cortile.sock -m '{"Action":"disable"}'
```

Let me know if this works for you.

**Comment by ahmeteid7** [comment]
```
wmctrl -s 0 && sleep 1 && ./send.sh -s /tmp/cortile.sock -m '{"Action":"disable"}'
bash: ./send.sh: No such file or directory
```
sorry what is ./send.sh? do u mean i create file with that name? if that what I script in it

**Comment by leukipp** [comment]
The script can be found in the assets folder: https://github.com/leukipp/cortile/blob/main/assets/scripts/send.sh

You can also try it without the script via...
```bash
echo '{"Action":"enable"}' | nc -U /tmp/cortile.sock.in
```
...and you may have to install `nc` (Netcat) on your distro if it's not already installed.

Details are explained in the [socket](https://github.com/leukipp/cortile#communication-) section of the README file.

**Comment by ahmeteid7** [comment]
i found the script and it worked very good
