### ISSUE TITLE
readme vs reality minor discrepencies 

### ISSUE THREAD

**Issue by CouldBeThis** [leukipp/cortile#4]
I do not know much about go but I thought I would let you know that on my system your docs have an error. 

I built from remote source as specified in readme and it seemed to be successful but I couldn't go on with the instructions. It turned out that instead of `~/.go/bin/cortile`, the correct location was `~/go/bin/cortile` which I found by looking at the results of `go env`. IDK why.

Also I wasn't clear from the docs if the file `~/.config/cortile/config.toml` was supposed to have been created during the set up? I think it was not created at all, or it was created empty. 

Any way I did get past both and then it looks like it runs as expected. 

`go version go1.18.3 linux/amd64` - can't offer much insight regarding causes of the above.

**Comment by leukipp** [comment]
Thanks for the feedback, I updated the [README](https://github.com/leukipp/cortile/blob/main/README.md) and the first beta release ([v1.0.0b1](https://github.com/leukipp/cortile/releases/tag/v1.0.0b1)) fixes the config issue.
