### ISSUE TITLE
How i can make disable+fullscreen mode?

### ISSUE THREAD

**Issue by ahmeteid7** [leukipp/cortile#41]
i wish when i disable or exit cortile , it exit with fullscreen mode.
can one key binding with two functions?if yes how i can do that in config?

**Comment by ahmeteid7** [comment]
i tried that and worked.
```
 echo '{"Action":"enable"}' | nc -U /tmp/cortile.sock.in
sleep 1
echo '{"Action":"layout_fullscreen"}' | nc -U /tmp/cortile.sock.in
```
and in keyword app i made ctrl+shift+0 to run it to enable+fullscreen.
and for disable+fullscreen 
```
echo '{"Action":"layout_fullscreen"}' | nc -U /tmp/cortile.sock.in
    sleep 1
 echo '{"Action":"disable"}' | nc -U /tmp/cortile.sock.in

```
and make shift+ctrl+. to run it.

for exit from cortile with fullscreen i tried that:
i do toggle launcher and pined it to panel with that script:
```
if pgrep -f "/home/eid/cortile" > /dev/null; then
    # The application is running, so let's kill it
    echo '{"Action":"layout_fullscreen"}' | nc -U /tmp/cortile.sock.in
    sleep 1
    pkill -f "/home/eid/cortile"
    
else
    /home/eid/cortile &
```

**Comment by thiswillbeyourgithub** [comment]
I'm sorry I must be missing some brain cells but I don't have any cortile.sock.in file in /tmp. Is there something I must do to enable this feature? I'm REALLY missing the ability to toggle layouts. It's making cortile awkward to use.

**Comment by leukipp** [comment]
@thiswillbeyourgithub 
The socket communication does not exist any more and was replaced with dbus as mentioned here: https://github.com/leukipp/cortile/issues/51#issuecomment-2288293302

You may want to create a new issues with your specific use case and requirements.
Maybe the feature you need does not require any sophisticated external communication.

In general you can directly use [dbus to communicate](https://github.com/leukipp/cortile?tab=readme-ov-file#addons-) with cortile, or use the build-in dbus client. e.g.:
```bash
 cortile dbus -method ActionExecute layout_maximized 0 0
```
In case you need extended custom logic you may want to have a look into the examples folder of the cortile python bindings: https://github.com/leukipp/cortile-addons
