### ISSUE TITLE
cortile release v2.3.2 crashes on start with GLIBC not found

### ISSUE THREAD

**Issue by ahmeteid7** [leukipp/cortile#42]
i'm using the develop version and it's working good with me, i tried the last release 2.3.2 amd64.tar.gz, but i get that:
```
./cortile
./cortile: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cortile)
./cortile: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./cortile)
```

**Comment by leukipp** [comment]
Related:
- Issue: https://github.com/golang/go/issues/58550
- Commit: https://github.com/leukipp/cortile/commit/576bdcdcd2115f549067ababb17622c78f1b7a28

**Comment by leukipp** [comment]
Does [v2.3.3](https://github.com/leukipp/cortile/releases/tag/v2.3.3) fix the issue?

**Comment by ahmeteid7** [comment]
> Does [v2.3.3](https://github.com/leukipp/cortile/releases/tag/v2.3.3) fix the issue?

yes, that fix it, great job
