### ISSUE TITLE
how to enable it on second monitor?

### ISSUE THREAD

**Issue by Fuckingnameless** [leukipp/cortile#47]
it only seems to work with primary display for me

**Comment by leukipp** [comment]
Please run cortile with `cortile -v` and provide the first ten lines of the output. You should see some Screens/Desktops logs, which will show if the second monitor was recognized.

Keep in mind, that if you have `tiling_enabled = false` in the toml.config you have to enable tiling per screen.
In general keyboard shortcuts (e.g. for tiling/untiling events) are executed on the screen where you pointer currently is located.

**Comment by leukipp** [comment]
Please provide additional information if this issue still exists.

**Comment by Fuckingnameless** [comment]
$ cortile -v
cortile already running (resource temporarily unavailable)
