### ISSUE TITLE
Option to disable window decorations only in fullscreen layout

### ISSUE THREAD

**Issue by Gutsosan** [leukipp/cortile#52]
Hello, i just found out about your window tiling project and i couldn't be more happy and amazed.
You 've done an amazing job and it's exactly what i was looking for.

The only thing missing, as the titles says, is the option to disable window decorations only in fullscreen layout.

I am aware of the option to completely disable window decorations, but i'd like to keep it just for fullscreen windows.
I would not ask for this, just to satisfy my personal needs, but since you have a similar option already coded, i guess and i hope that it is not hard to include one more option for fullscreen only.

Thanks again for your great work!!

**Comment by leukipp** [comment]
I want to keep this as general as possible, what about new layouts?
- **maximized**: window maximized inside tiling area
  - with/without decoration, same as the current "fullscreen" mode, considering desktop margins
- **fullscreen**: window fullscreen over screen
  - without decoration, ignoring desktop margins, overlaying panel bars

Would this satisfy your requirements?

**Comment by Gutsosan** [comment]
> I want to keep this as general as possible, what about new layouts?
> 
> * **maximized**: window maximized inside tiling area
>   
>   * with/without decoration, same as the current "fullscreen" mode, considering desktop margins
> * **fullscreen**: window fullscreen over screen
>   
>   * without decoration, ignoring desktop margins, overlaying panel bars
> 
> Would this satisfy your requirements?

Sorry for the late reply.

Sure, those options sound great.

I have enabled the titleless_maximize option in xfce settings and use the top panel bar as window title with buttons and the appmenu, so that option would make my desktop feel the same as now with a great tiling manager on top, as yours is.

Your program is already great, but this addition would make it perfect for me if that doesnt put you into any unnecessary trouble.

Cheers and thanks again!

**Comment by Gutsosan** [comment]
I noticed that when i remove window decorations, when i open a new window some empty bars appear on top or bottom of the window most of the times, at the size of the window title bar. I noticed that the problem doesnt appear by disabling the compositor (using xfce DE).
Maybe instead of making new layouts with disable/enable window decoration option, it would be better to make a new layout with maximized windows and take advantage of the DE's setting for titleless windows.

**Comment by leukipp** [comment]
Please have a look into the latest [v2.5.0](https://github.com/leukipp/cortile/releases/tag/v2.5.0) release and the related feature #58 with the new layouts.
The new layouts are for general purpose, and may be not exactly what you have been looking for.

Just let me know.

**Comment by noraef** [comment]
Having what Gutsosan requests could easily be achieved by a setting automatically activating maximize tiling mode when there is only a single non-floating window, and going back to the preferred tiling mode as soon as another non-floating window appears.

XFCE, for instance, has a setting to deactivate decorations and window title for any app that is maximized, as Gutsosan tells in the third post of this thread.

Automatically maximizing a single non-floating window would thus automatically make its decoration and title disappear, for those to appear back as soon as a second non-floating window appears (I guess the ideal would then be to automatically activate the preferred tiling mode; or maybe the previously used tiling mode on this workspace, otherwise).

**Comment by leukipp** [comment]
> XFCE, for instance, has a setting to deactivate decorations and window title for any app that is maximized, as Gutsosan tells in the third post of this thread.

Actually the build in XFCE feature will not work, as cortile has to unmaximize every window (e.g. to account for desktop margins) and therefore the window will not be "EWMH recognized" as maximized.

I added the feature that decoration can be toggled and remembered per layout (e.g. no decoration when cortile maximized layout is active).

For further details see #62.
