### ISSUE TITLE
How to change the key binding from Ctrl + Shift to Super Key?

### ISSUE THREAD

**Issue by radiaated** [leukipp/cortile#53]
Hello, I am on Linxu Mint XFCE. 

I keep triggering the tiles events whenever I try to select the text by pressing "Control + Shift + Left/Right Arrow Key". I tried changing the "Control + Shift" part of the key binding to "Mod4" and it keeps opening the menu at the bottom.  So i would want to know if there's a proper way to do it without breaking anything. Thank you.

**Comment by leukipp** [comment]
> I tried changing the "Control + Shift" part of the key binding to "Mod4" and it keeps opening the menu at the bottom.

I'm not sure what you mean with the menu on the button. Did you check if your key binding is already in use by some operating system shortcuts? Cortile may also print some warnings (of already binded keys) if you start it over the terminal.

If you replace the "Control + Shift" bindings with a "Mod*" key, you may also need to temporary comment this two lines:
https://github.com/leukipp/cortile/blob/b92d436382ca78e71222e11d087b1c9041718ac9/config.toml#L182-L186

**Comment by radiaated** [comment]
Pressing windows/super key opens the start menu on the panel is what i meant to say. I wanted to know if there's a support to set Super key to be the mod key or do I need to disable the OS's binding for super key in order for this to work?

**Comment by leukipp** [comment]
> I wanted to know if there's a support to set Super key to be the mod key or do I need to disable the OS's binding for super key in order for this to work?

Yes, any kind of overlapping and existing key bindings have to be removed, before you can register them to cortile.

Did you also try "Control + Mod4 + *" or "Mod4 + Shift + *"?

**Comment by radiaated** [comment]
> Did you also try "Control + Mod4 + *" or "Mod4 + Shift + *"?

only Mod4 like in i3wm

**Comment by leukipp** [comment]
Please comment the existing "Mod4" bindings (as mentioned above) and try this key binding: 
```toml
# Toggle between enable and disable on the current screen.
toggle = "Mod4-T"
```

This works on Ubuntu XFCE, you may have to remove some existing shortcuts.

**Comment by radiaated** [comment]
I manually unbind the existing Window Manager's shortcut keys for Super Key that were causing conflict as it said it the log and gave them new bindings as I liked. The way to do it remove the existing OS's binding and now it works. Thank you.
