### ISSUE TITLE
Feature Suggestions: Workspace specific + Toggle Fill

### ISSUE THREAD

**Issue by ryuukk** [leukipp/cortile#55]
Nice work on this utility, i have however few suggestions to make:

- option to make it work only in specific workspace
- option to fill/restore (toggle) either horizontal/vertical

![image](https://github.com/leukipp/cortile/assets/44361234/d69ce113-f3ce-412d-9d25-77c104ca74cb)

Use case: i have text editor at the top, and usually a terminal with tabs at the bottom, i would like to be able to toggle that

Thanks

**Comment by leukipp** [comment]
> option to fill/restore (toggle) either horizontal/vertical

The layout in the middle of your graphic can be archived by choosing a horizontal layout and decreasing the number of masters to zero.  You can then safely switch to another layout to toggle between the first/last and middle layout of your graphic.

> option to make it work only in specific workspace

Cortile supports tiling per workspace, each enable/disable action only affects the active workspace. Or did you mean something else?

**Comment by leukipp** [comment]
You can start cortile without tiling by setting this config entry to false:
https://github.com/leukipp/cortile/blob/ad15ebd73f8c9cab7131bb4ba88cc3a1f19c00d1/config.toml#L10

Afterwards enable tiling only on your specific workspace.

The tiling states per workspace will be cached as described here: https://github.com/leukipp/cortile/issues/44  
To reset any existing cached states, you may have to delete the `/home/USER/.cache/cortile/` folder before.
