### ISSUE TITLE
Window dimenions are misread when using Reaper

### ISSUE THREAD

**Issue by japostoles** [leukipp/cortile#59]
When using Reaper  (www.reaper.fm/) it seems to add padding to the top of the window equal to the title bar, almost as if the title bar is considered part of the window.  This creates too much padding above, and cropping below:

![image](https://github.com/leukipp/cortile/assets/235242/c98e276c-27f5-4d64-8c1a-9fb1ef7d5aa1)

**Comment by leukipp** [comment]
I can confirm this issue, e.g. the same happens to [FileZilla](https://filezilla-project.org/).
I will have a look into this.

**Comment by leukipp** [comment]
Fixed with [v2.5.1](https://github.com/leukipp/cortile/releases/tag/v2.5.1),
