### ISSUE TITLE
Unexpected behaviour with XFCE  Dual monitor with Focus Follows Mouse enabled

### ISSUE THREAD

**Issue by pipe-organ** [leukipp/cortile#61]
I really like this app, but I'm having an issue when using Cortile with my dual monitor setup. I have "Focus follows mouse" enabled in the XFCE Window Manager. However, when I move my mouse from screen 1 to screen 2 and try to open Thunar or Terminal, it still opens on screen 1, and the same happens in reverse. And even if I click on windows on screen 2, it still adds new terminal or window in screen 1. Can anyone help me resolve this? Thanks!

**Comment by leukipp** [comment]
Cortile remembers and restores the window positions and states starting with version [v2.3.0](https://github.com/leukipp/cortile/releases/tag/v2.3.0). See feature request #21.

> However, when I move my mouse from screen 1 to screen 2 and try to open Thunar or Terminal, it still opens on screen 1...

As cortile will move the window back to the latest screen the "Focus follows mouse" feature will not work.

You can disable caching via `cortile -cache 0`, but you will also lose the functionality that tiling layouts are restored. 
If you really need it you can also use a version smaller v2.3.0.

**Comment by pipe-organ** [comment]
Actually cortile -cache 0 works well. Since remembering state is not crucial for me. This is great. Thanks for adding this option.
