### ISSUE TITLE
Cortile stops working after opening tab in Gnome Terminal

### ISSUE THREAD

**Issue by grizzlymannn** [leukipp/cortile#64]
I'm on Linux Mint 22 Cinnamon.  Whenever I open a tab in Gnome terminal Cortile hangs.  Windows no longer snap and it doesn't respond to `systemctl --user restart cortile.service`.  Doing a  `pkill -9` does work though.

Please let me know if there is any info or logs that would be helpful.

**Comment by leukipp** [comment]
Please remove the existing `/tmp/cortile.log` file.
Then, start using `cortile -v` and reproduce the error.

Once done, share the log file here so I can review it.

**Comment by leukipp** [comment]
The default [keyboard shorctuts](https://help.gnome.org/users/gnome-terminal/stable/adv-keyboard-shortcuts.html.en) of gnome terminal may also interfere with cortile.
You may just disable tiling when using `Ctrl+Shift+T` to open a new tab.

You should start cortile on a terminal (instead as a service), to observe possible warnings related to keybindings.
Also check the [README](https://github.com/leukipp/cortile?tab=readme-ov-file#shortcuts)  keyboard shortcuts section.

Please have a look into this and let me know.

**Comment by grizzlymannn** [comment]
Here's the [log output](https://gist.github.com/grizzlymannn/5af6af3422aae3c89b6fa12229a0962f).  At 2024-08-14T16:48:40-04:00 I clicked `File` then `New Tab` in Gnome Terminal.  It looks like it got stuck in a loop until I killed it with `pkill -9 cortile` from another terminal.

**Comment by leukipp** [comment]
It seems like gnome-terminal doesn't like it when the window size limits (minimum width/height) are set, as it tries internally to resize the window back, which causes the loop behavior you described.

I have disabled this feature for now for mutter based window managers. Please install the next cortile release (when published) and let me know if it works.

**Comment by leukipp** [comment]
Please check [v2.5.1](https://github.com/leukipp/cortile/releases/tag/v2.5.1).

**Comment by grizzlymannn** [comment]
Looks like that fixed it. Thank you!
