### ISSUE TITLE
how i can get the quarter layout in cortile?

### ISSUE THREAD

**Issue by ahmeteid7** [leukipp/cortile#7]
I can't get quarter layout in cotile, the mater window get the half and others share the other half, it's the default state in the app or may i miss something?

**Comment by leukipp** [comment]
In general only the master-slave proportion can be changed, not each window individually (see [Known Issues](https://github.com/leukipp/cortile#Known_Issues)).

Default settings should be 60% master, 40% slave area. You can find it in the [config.yaml](https://github.com/leukipp/cortile/blob/main/config.toml), defined as `proportion = 0.6`.
After startup you can also just change the proportion by using the mouse <kbd>Alt</kbd>+<kbd>Right-Click</kbd>.

**Comment by ahmeteid7** [comment]
that is very good, u r right , i can get the quarter layout by increase the number of master pages to two. Thanks
