### ISSUE TITLE
Changing keybinds only messes things in Metacity Gnome Flashback in Debian 12

### ISSUE THREAD

**Issue by lobaluna** [leukipp/cortile#72]
Hi, devs

I have tried to change the control+shift keybindings to Super_L+Alt+KPn, but it is all messed up. As soon as I touch the Super_L+Alt keys (but not the KPn), the layouts start to change crazily.

Of course, I disabled the two keybinding that come prebuilt in Metacity (Super+Left and Super+Right). I started with the four keybindings for changeing the layout, as a matter of test, but I had no luck.

I used xev to check the right name of key, which is Super_L.

Is there any thing wrong with the application?

**Comment by leukipp** [comment]
Please use the latest version and run `cortile -v`  in a terminal, check the KEYS output and see if any warnings appears regarding keys that are invalid/already binded. Then provide the logs and your current config.toml.

Keep also in mind that `Super_L = Mod4` and it is used to bind additional keys as defined here:
https://github.com/leukipp/cortile/blob/376e386027e922ac5d1322da7f0cf3e263e98a54/config.toml#L192

You have to change or delete the `mod_*` bindings, if you don't want to use it.

**Comment by lobaluna** [comment]
Thank you. OK. Just give me a couple of days to report you back. Thanks again!

**Comment by lobaluna** [comment]
Your indications helped me. Thanks! I commented half the keybindings, tested it using C-KP_n shortcuts, and it worked perfectly.

Since I use LibreOffice and many shortcuts there are of the kind Ctrl+Shift+, I cannot have them "kidnapped" by Cortile ;D

Great, great program of yours, this Cortile. Thanks again.
