### ISSUE TITLE
cortile tile for xfce not working for css tweaked firefox

### ISSUE THREAD

**Issue by spupuz** [leukipp/cortile#73]
i have a tweaked firefox that has the address bar at the same level of close button, this is done with css modification, cortile is note correctly managing that, firefox does not adhere to the cortile rules.

![image](https://github.com/user-attachments/assets/d43899b9-ab7d-4268-ab39-78c42bc0616a)

**Comment by leukipp** [comment]
Cortile uses [xgb](https://github.com/jezek/xgb) to communicate with the X server. Any customs modifications on the client side (like css) are not part of the EWMH specification and can't be accessed.

If you want to use cortile, consider removing any client side custom decorations.
