### ISSUE TITLE
Feature Request: A way to toggle back and forth layouts

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [leukipp/cortile#77]
Hi,

[As requested here](https://github.com/leukipp/cortile/issues/41#issuecomment-2429792277), I'm looking for a feature and not quite sure how to proceed in cortile.

Basically I'm coming from the i3wm world and got used to a feature called "auto_back_and_forth" which simply means that doing twice a shortcut brings you back to the previous state.

Specifically I'm after a way so that the shortcut to maximize/fullscreen an app, when pressed a second time, would go back to the previous layout (= unmaximize / exit fullscreen).

Edit: rereading the owner's comment it appears clear that this can probably simply done with a simple script so if you could just tell me that specific commands I should familiarize myself with to do it I can probably manage without taking too much of your time

**Comment by leukipp** [comment]
I will think about, on how to add this directly into cortile.

In the meantime, I added a cortile-addons example that toggles between `maximized` and the previous layout when cortile is enabled and `<ctrl> + <alt> + <j>` is pressed:
https://github.com/leukipp/cortile-addons/blob/main/examples/toggle_layout_with_keybindings.py

If you have problems getting the script to run or adapting it to your needs, just create a new issue in the [cortile-addons](https://github.com/leukipp/cortile-addons/issues) repository.

**Comment by leukipp** [comment]
You can now use #78, with only two layouts defined in the cycler. If you need extended custom logic, feel free to have a look into the example addon scripts.
