### ISSUE TITLE
How to switch windows between tiling and floating

### ISSUE THREAD

**Issue by zhj0887** [leukipp/cortile#81]

**Comment by leukipp** [comment]
You can use the build in OS features. e.g. On XFCE you can right click on the window title and select "Always on Top".
For sticky/pinned windows that always move to the active workspace you can use "Always on Visible Workspace".

**Comment by zhj0887** [comment]
Thank you for the reply.
My English is not good. I'm relying on a translation tool, so you may have misunderstood what I meant.
ignore windows Toggle tiling and non-tiling in use
Like bspwm or dwm toggle floating.

**Comment by leukipp** [comment]
No Problem, I still think we are talking about the same thing.
Floating windows are part of the EWMH specification, so cortile doesn't have dedicated shortcut keys to set them.

You can just set them as part of your OS (Operating System) features. The "[_NET_WM_STATE_ABOVE](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html) indicates that the window may placed in the "above" layer of windows". Which means it is floating and the window will not be tiled.

So when you are using a non tiling window manager, there must be an option to set the window to be "Always on Top", which cortile will recognize to handle it correctly. 

Let me know what system and window manager you are using and also feel free to articulate your request in your native language. Maybe someone from the community will be able to help us out.

**Comment by zhj0887** [comment]
Thanks for your patience in answering my questions
I'm using archlinux openbox
I've found a solution to the problem
wmctrl -r :ACTIVE: -b toggle,above
xdotool getactivewindow windowstate --toggle above
Just after switching to floating, the window decoration did not recover
