### ISSUE TITLE
[Feature Request] Colored border on window focus

### ISSUE THREAD

**Issue by dev-inside** [leukipp/cortile#82]
Hi,
I really like Cortile and everything works great with Budgie, but I would love to add a colored Border around the focused Window. I've got really used to that feature from Cosmiq Desktop and other Window Managers. If possible, I would love to  define border-color and width.

**Comment by leukipp** [comment]
Implementing custom borders on active windows across all operating systems and window managers supported by cortile is not feasible in a proper manner. Generally, the appearance of windows (e.g. focused borders) is managed by the window manager itself, while X only provides limited features to change them.

Depending on your specific setup, you may already have settings available to modify how active windows are displayed. For instance, in XFCE, you can adjust the opacity of inactive windows to "highlight" the currently focused window.
